name: Auto Bump and Tag

on:
  push:
    branches:
      - main

jobs:
  tagger:
    name: "Bump and Tag"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b #v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


#refactor:patch:Code Refactoring
#build:patch:Builds
#ci:patch:Continuous Integrations
#docs:patch:Documentation
#
#revert:minor:Reverts
#
#
#
#Patch:
#  - fix
#  - perf
#
#Minor:
#  - feat
#  -
#
#None:
#  - style
#  - test
#  - chore
#  - refactor
#  -
