name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      skip_release: ${{ steps.check.outputs.skip_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Get changed files'
        id: 'get_files'
        uses: masesgroup/retrieve-changed-files@v3
      - name: 'Checking files'
        id: 'check'
        run: |
          if echo ${{ steps.get_files.outputs.all }} | tr ' ' '\n' | grep -Ev $(grep -Ev '^#|^$' .github/files_that_skip_release | tr '\n' '|' | sed 's/|$//'); then
            echo "Not skipping release"
            echo "skip_release=false" >> $GITHUB_OUTPUT
          else
            echo "Skipping release - default"
            echo "skip_release=true" >> $GITHUB_OUTPUT
          fi


  tag:
    needs: check_files
    if: github.ref == 'main' && github.event.pull_request.merged == true && needs.check_files.outputs.skip_release == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

  build_and_release:
    needs: tag
    if: github.ref == 'main' && github.event.pull_request.merged == true && needs.check_files.outputs.skip_release == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
          cache: false
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
