name: CI

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}
  pull_request:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Printer
        run: |
          echo "HERE"
